name: 🐛 Bug report
description: Create a report to help us improve
labels: [bug,needs-triage]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: Please provide a clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: To Reproduce
    description: "Steps to reproduce the behavior:"
    value: "1. Go to '...'\n
2. Click on '....'\n
3. Scroll down to '....'\n
4. See error"
- type: textarea
  attributes:
    label: Additional information
    description: If applicable, add screenshots or any other context to help explain the situation.

- type: checkboxes
  id: platforms
  attributes:
    label: "Applies to the following platforms:"
    options:
    - label: UWP
    - label: WPF
    - label: WinUI

- type: textarea
  attributes:
    label: About your setup
    description: Please provide the following to help 
    value: "- Visual Studio Version:  \n
- WinTS Wizard Version: \n
- WinTS Template Version: \n
- Windows Build: "
